"""add tmdb runtime cast fields

Revision ID: 715c52a66000
Revises: 0da335019721
Create Date: 2026-05-14 19:35:46.395521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715c52a66000'
down_revision = '0da335019721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('runtime', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cast', sa.String(length=300), nullable=True))
        batch_op.create_unique_constraint('uq_movies_tmdb_id', ['tmdb_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint('uq_movies_tmdb_id', type_='unique')
        batch_op.drop_column('cast')
        batch_op.drop_column('runtime')
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###
